version: '3.2'

services:
  postgresql:
    volumes:
      - postgresql:/var/lib/postgresql/data
  redis:
    volumes:
      - redis:/data

volumes:
  postgresql:
    driver: local
  redis:
    driver: local