version: '3.2'

services:
  postgresql:
    image: postgres:13.3
    ports:
      - 5432
    environment:
      - POSTGRES_DB=kotlink
      - POSTGRES_USER=kotlinkuser
      - POSTGRES_PASSWORD=kotlinkpass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 15s
      timeout: 30s
      retries: 3
  redis:
    image: redis:6.2.4
    ports:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 15s
      timeout: 30s
      retries: 3