version: '3.2'

services:
  postgresql:
    build:
      context: postgresql
    ports:
      - 55432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kotlink
      - POSTGRES_USER=ktuser
      - POSTGRES_PASSWORD=ktpass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 15s
      timeout: 30s
      retries: 3


volumes:
  postgresql:
    driver: local