apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kotlink
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kotlink
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
