apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kotlink.fullname" . }}
type: Opaque
stringData:
  google_oauth_client_id: {{ .Values.secret.google_oauth_client_id }}
  google_oauth_client_secret: {{ .Values.secret.google_oauth_client_secret }}
  spring_datasource_url: jdbc:postgresql://postgres:5432/kotlink?useSSL=false&connectTimeout=3&socketTimeout=3
  spring_datasource_username: {{ .Values.postgresql.postgresqlUsername | quote }}
  spring_redis_sentinel_master: mymaster
  spring_redis_sentinel_nodes: redis-announce-0:26379, redis-announce-1:26379, redis-announce-2:26379
  actuator_user_name: {{ .Values.secret.actuator_user_name }}
  actuator_user_password: {{ .Values.secret.actuator_user_password }}