{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kotlink.serviceAccountName" . }}
  labels:
{{ include "kotlink.labels" . | indent 4 }}
{{- end -}}
